### ISSUE TITLE
Stardog cannot write on the persistent volume

### ISSUE THREAD

**Issue by fungiboletus** [stardog-union/helm-charts#75]
When using the default configuration, stardog does not have the permission to write ont he persistent volume. This is because the persistent volume is owned by root and stardog doesn't use run with the root user by default.

```
STARDOG_HOME '/var/opt/stardog/' is not writeable by the current user
```

A workaround is to run stardog as root:

```yaml
  securityContext:
    enabled: true
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
```

A better solution would be to use the busybox init container, not only when the cluster is enabled, to change the permissions before stardog starts.
